import 'package:http/http.dart' as http;
import 'package:amplify_flutter/amplify_flutter.dart'; // For safePrint

/// --------------------------------------------------------------------------
/// API Service (Handles general network requests)
/// --------------------------------------------------------------------------
class ApiService {
  /// Fetches JSON data from a given pre-signed S3 URL.
  ///
  /// The [presignedUrl] is a secure, temporary URL generated by AWS S3.
  /// This function performs a standard HTTP GET request to retrieve the
  /// content of the file pointed to by the URL.
  Future<String> fetchJsonFromPresignedUrl(String presignedUrl) async {
    safePrint('🌎 Fetching data from pre-signed URL...');
    
    try {
      // Create a Uri object from the URL string.
      final uri = Uri.parse(presignedUrl);

      // Send an HTTP GET request to the URL.
      final response = await http.get(uri);

      // Check if the request was successful (status code 200 OK).
      if (response.statusCode == 200) {
        safePrint('✅ Successfully fetched data.');
        // The body of the response contains the file content.
        return response.body;
      } else {
        // If the server did not return a 200 OK response, throw an error.
        safePrint('❌ Failed to fetch data. Status code: ${response.statusCode}');
        safePrint('Response body: ${response.body}');
        throw Exception('Failed to load data from the provided URL.');
      }
    } catch (e) {
      // Catch any other errors during the network request.
      safePrint("❌ An error occurred while fetching data: $e");
      throw Exception('Could not fetch data. Check your network connection and the URL.');
    }
  }
}
